import type { 
  Unit, 
  Invoice, 
  AccessEntry, 
  AmenityReservation, 
  MaintenanceOrder 
} from '../types/condominium';

export const mockUnits: Unit[] = [
  {
    id: 'u-402',
    number: '402',
    block: 'Bloco A',
    tower: 'Torre Sol',
    squareMeters: 140,
    residentsCount: 4,
    residentType: 'Proprietário',
    ownerName: 'Carlos Eduardo Duarte',
    contactName: 'Carlos Eduardo Duarte',
    parkingSpot: 'G-14',
    parkingFloor: 'Subsolo 1',
    financialStatus: 'Condomínio em Dia',
    bioSyncCount: '4/4',
    bioSyncActive: true,
    hasPet: false,
    vehicleModel: 'Toyota Corolla Cross • Prata',
    vehiclePlate: 'BRA-4E29',
    smartLockerPackage: {
      drawerNumber: '#08',
      description: '1 Encomenda no Smart Locker • Código PIN enviado ao morador',
      status: 'Pronto',
    },
    members: [
      { id: 'm-1', name: 'Carlos E. Duarte', role: 'Responsável Titular', initials: 'CD', bioSyncActive: true, isMainContact: true },
      { id: 'm-2', name: 'Helena Duarte', role: 'Cônjuge', initials: 'HD', bioSyncActive: true },
      { id: 'm-3', name: 'Lucas Duarte (14)', role: 'Filho dependente', initials: 'LD', bioSyncActive: true },
      { id: 'm-4', name: 'Beatriz Duarte (9)', role: 'Filha dependente', initials: 'BD', bioSyncActive: true },
    ]
  },
  {
    id: 'u-401',
    number: '401',
    block: 'Bloco A',
    tower: 'Torre Sol',
    squareMeters: 98,
    residentsCount: 2,
    residentType: 'Inquilino',
    ownerName: 'Roberto Vasconcelos',
    contactName: 'Marina Albuquerque',
    parkingSpot: 'G-12',
    parkingFloor: 'Subsolo 1',
    financialStatus: 'Condomínio em Dia',
    bioSyncCount: '2/2',
    bioSyncActive: true,
    hasPet: false,
    vehicleModel: 'Honda Civic • Preto',
    vehiclePlate: 'RIO-9A12',
    members: [
      { id: 'm-5', name: 'Marina Albuquerque', role: 'Titular Inquilina', initials: 'MA', bioSyncActive: true, isMainContact: true },
      { id: 'm-6', name: 'Felipe Albuquerque', role: 'Cônjuge', initials: 'FA', bioSyncActive: true }
    ]
  },
  {
    id: 'u-303',
    number: '303',
    block: 'Bloco A',
    tower: 'Torre Sol',
    squareMeters: 120,
    residentsCount: 3,
    residentType: 'Proprietário',
    ownerName: 'Rafael Cavalcanti',
    contactName: 'Rafael Cavalcanti',
    parkingSpot: 'G-08',
    parkingFloor: 'Térreo',
    financialStatus: 'Boleto a Vencer (Hoje)',
    bioSyncCount: '2/3',
    bioSyncActive: false,
    hasPet: true,
    petDescription: '1 Pet (Golden Retriever - Max)',
    vehicleModel: 'Jeep Compass • Branco',
    vehiclePlate: 'SPX-3K88',
    members: [
      { id: 'm-7', name: 'Rafael Cavalcanti', role: 'Responsável Titular', initials: 'RC', bioSyncActive: true, isMainContact: true },
      { id: 'm-8', name: 'Camila Cavalcanti', role: 'Cônjuge', initials: 'CC', bioSyncActive: true },
      { id: 'm-9', name: 'Gabriel Cavalcanti', role: 'Filho', initials: 'GC', bioSyncActive: false }
    ]
  },
  {
    id: 'u-108',
    number: '108',
    block: 'Bloco B',
    tower: 'Ipês',
    squareMeters: 85,
    residentsCount: 1,
    residentType: 'Inquilino',
    ownerName: 'Fernando Diniz',
    contactName: 'Juliana Mendes Ramos',
    parkingSpot: 'G-33',
    parkingFloor: 'Subsolo 2',
    financialStatus: 'Condomínio em Dia',
    bioSyncCount: '1/1',
    bioSyncActive: true,
    hasPet: false,
    vehicleModel: 'Hyundai HB20 • Cinza',
    vehiclePlate: 'KLP-1D90',
    members: [
      { id: 'm-10', name: 'Juliana Mendes Ramos', role: 'Titular', initials: 'JR', bioSyncActive: true, isMainContact: true }
    ]
  }
];

export const mockInvoices: Invoice[] = [
  {
    id: 'inv-1',
    unitNumber: '402',
    block: 'Bloco A',
    residentName: 'Carlos Eduardo Silva',
    description: 'Condomínio Ordinário + Água',
    dueDate: '10/Dez/2024',
    amount: 1150.00,
    status: 'liquidated',
    statusLabel: 'Liquidado via Pix',
    pixAuthenticated: true,
  },
  {
    id: 'inv-2',
    unitNumber: '101',
    block: 'Bloco B',
    residentName: 'Mariana Albuquerque',
    description: 'Condomínio Ordinário',
    dueDate: '10/Dez/2024',
    amount: 980.00,
    status: 'due_today',
    statusLabel: 'A Vencer Hoje',
    pixAuthenticated: false,
  },
  {
    id: 'inv-3',
    unitNumber: '305',
    block: 'Cobertura C',
    residentName: 'Rodrigo Santoro Mello',
    description: 'Taxa Ordinária + Fundo Reserva',
    dueDate: '10/Nov/2024 (-30d)',
    amount: 1840.50,
    status: 'overdue',
    statusLabel: 'Em Atraso — 2ª via enviada',
    pixAuthenticated: false,
    whatsappReminderSent: true,
  },
  {
    id: 'inv-4',
    unitNumber: '214',
    block: 'Bloco A',
    residentName: 'Patrícia Lima Fontes',
    description: 'Condomínio Ordinário',
    dueDate: '10/Dez/2024',
    amount: 980.00,
    status: 'advance',
    statusLabel: 'Liquidado Antecipado',
    pixAuthenticated: true,
  }
];

export const mockAccessEntries: AccessEntry[] = [
  {
    id: 'acc-1',
    personName: 'Camila Rezende',
    photoUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDGUTyvDyXqUPOpkDhxqVkJFQj99TQzeZv73WSVJ-hGuwUqYJ8l5oMDZSteNPIoZUxt8Kdt74PWSB9R7Bwoh8gvcc01KXHtRkR30ExQyQ90VKyKjJbJsU15ND11eVWegiPEuUrPTDU1R-TpszLMJTfHmvQqHhdFdOoS6PE-xcq7RRnZoIDRyVmLsKtKBZogBOYvaIokriyHB8FxDRr2nxxYr7_DhzUJclLYlalgsRcruvOJLe3YXEzfdg',
    timestamp: '18:42:15',
    accessPoint: 'Portaria Pedestres A',
    destination: 'Torre B — Apto 1204',
    type: 'Morador Residente',
    authType: 'facial',
    authDetail: 'Reconhecimento Facial (0.24s)',
  },
  {
    id: 'acc-2',
    personName: 'Lucas Barreto',
    photoUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCb_tEK_i6jZJ9tt5kKwRmtrWMa4nsau7KFYbU-DV_kXmSMhvaKPwFz_PqH2eW2-HaULdN6Wvb9ExRwloyRErtBEZ93w_m0NU0lhtK86OPQAq8Hxf6aGu4AsDeP5CpXV6daJO-du_qGREijwsHHqy4vdPnoEaDfv-qRZJ5mZV95V1nZ5qKAQoyjN7BYR2t0SbpEHI4gl58FJ8e1xJKv2D0dJyL2LBULph6Ei6YEgDD6AkkW8SXo7GIA4Q',
    timestamp: '18:38:02',
    accessPoint: 'Totem QR Portaria',
    destination: 'Torre A — Apto 501',
    type: 'Convidado QR Válido',
    authType: 'qr',
    authDetail: 'Convite Digital Gerado pelo App',
  },
  {
    id: 'acc-3',
    personName: 'Carlos E. (iFood)',
    photoUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBUfLszZ81nxeS6VgYfwDv3cT6xKnRmgkC6KPYM25ZK1NKgu_djRWrsMxBFDI1jdbjhD0i83rOzdaPw0HDP0rasTalCP3No5kfW-WjgZA49810DfOHIKkL5X7TtCQOm8zjWqZjz2NNbWeCvZtR6Y_fTB9Sk9LSYy3xdkhCF88uiyzNd0qkV6X6Yx_6Q0TIwEfXf814PayDelA_UgNrwlw85sqlPCGbufUnSJf-yQ8frpMiIY9ataP7SEQ',
    timestamp: '18:31:40',
    accessPoint: 'Eclusa de Delivery',
    destination: 'Torre A — Apto 308',
    type: 'Liberação Temp. (15 min)',
    authType: 'delivery',
    authDetail: 'Documento CNH auditado',
  }
];

export const mockReservations: AmenityReservation[] = [
  {
    id: 'res-1',
    spaceName: 'Salão de Festas Principal',
    emoji: '🎉',
    date: '2026-10-10',
    startTime: '18:00',
    endTime: '23:30',
    dateStr: 'Sáb, 10 Out • 18:00 às 23:30',
    responsibleName: 'Família Duarte',
    unitNumber: 'Apto 402',
    status: 'Aprovado / Taxa Paga',
    statusType: 'success',
  },
  {
    id: 'res-1b',
    spaceName: 'Espaço Gourmet & Churrasqueira',
    emoji: '🥩',
    date: '2026-10-10',
    startTime: '12:00',
    endTime: '22:00',
    dateStr: 'Sáb, 10 Out • 12:00 às 22:00',
    responsibleName: 'Renato Siqueira',
    unitNumber: 'Apto 204',
    status: 'Aprovado / Taxa Paga',
    statusType: 'success',
  },
  {
    id: 'res-1c',
    spaceName: 'Quiosque da Piscina',
    emoji: '🏊‍♂️',
    date: '2026-10-10',
    startTime: '09:00',
    endTime: '18:00',
    dateStr: 'Sáb, 10 Out • 09:00 às 18:00',
    responsibleName: 'Carla Nogueira',
    unitNumber: 'Apto 301',
    status: 'Aprovado',
    statusType: 'success',
  },
  {
    id: 'res-2',
    spaceName: 'Espaço Gourmet & Churrasqueira',
    emoji: '🥩',
    date: '2026-10-12',
    startTime: '12:00',
    endTime: '17:00',
    dateStr: 'Seg, 12 Out • 12:00 às 17:00 (Feriado)',
    responsibleName: 'Marcos Vianna',
    unitNumber: 'Apto 115',
    status: 'Aprovado',
    statusType: 'success',
  },
  {
    id: 'res-3',
    spaceName: 'Quiosque da Piscina',
    emoji: '🏊‍♂️',
    date: '2026-10-18',
    startTime: '10:00',
    endTime: '16:00',
    dateStr: 'Dom, 18 Out • 10:00 às 16:00',
    responsibleName: 'Roberta Silveira',
    unitNumber: 'Apto 74B',
    status: 'Aguardando Caução',
    statusType: 'warning',
  },
  {
    id: 'res-4',
    spaceName: 'Salão de Festas Principal',
    emoji: '🎉',
    date: '2026-10-24',
    startTime: '19:00',
    endTime: '23:59',
    dateStr: 'Sáb, 24 Out • 19:00 às 23:59',
    responsibleName: 'Juliana Paes',
    unitNumber: 'Apto 101',
    status: 'Aprovado / Taxa Paga',
    statusType: 'success',
  },
  {
    id: 'res-5',
    spaceName: 'Espaço Gourmet & Churrasqueira',
    emoji: '🥩',
    date: '2026-09-26',
    startTime: '13:00',
    endTime: '20:00',
    dateStr: 'Sáb, 26 Set • 13:00 às 20:00',
    responsibleName: 'Carlos Magno',
    unitNumber: 'Apto 202',
    status: 'Aprovado / Taxa Paga',
    statusType: 'success',
  },
  {
    id: 'res-6',
    spaceName: 'Salão de Festas Principal',
    emoji: '🎉',
    date: '2026-11-07',
    startTime: '18:00',
    endTime: '23:00',
    dateStr: 'Sáb, 07 Nov • 18:00 às 23:00',
    responsibleName: 'Patricia Mendes',
    unitNumber: 'Apto 501',
    status: 'Aprovado',
    statusType: 'success',
  }
];

export const mockMaintenanceOrders: MaintenanceOrder[] = [
  {
    id: 'mo-1',
    code: 'OS #8491',
    title: 'Inspeção Preventiva Elevadores',
    location: 'Torre B & C • Rotina mensal concluída',
    description: 'Inspeção Preventiva ATLAS (Elevadores Torre A)',
    status: '100% Concluído',
    statusType: 'completed',
    progressPercentage: 100,
    scheduledTime: 'Finalizado hoje às 11:20',
    priority: 'Preventiva',
    technicians: [{ initials: 'MS', name: 'João' }, { initials: 'LA', name: 'Carlos' }],
  },
  {
    id: 'mo-2',
    code: 'OS #8502',
    title: 'Reparo Bomba de Recalque Subsolo 2',
    location: 'Hidráulica Central • Troca de selo mecânico',
    description: 'Hidráulica Central • Previsão 16:30',
    status: '67% Em Andamento',
    statusType: 'in_progress',
    progressPercentage: 67,
    scheduledTime: 'Previsão: Hoje, 17:30 (Etapa 2 de 3)',
    priority: 'Normal',
    technicians: [{ initials: 'EN', name: 'Marcos' }],
  },
  {
    id: 'mo-3',
    code: 'OS #8510',
    title: 'Substituição LED Garagem G1',
    location: '16 luminárias tubulares • Almoxarifado OK',
    description: 'Prioridade Média • Aguardando Material',
    status: 'Agendado',
    statusType: 'scheduled',
    progressPercentage: 0,
    scheduledTime: 'Agendado para Sexta, 08:00',
    priority: 'Média',
    materialsReserved: true,
    technicians: [],
  },
  {
    id: 'mo-4',
    code: 'OS #8515',
    title: 'Limpeza Semestral Caixas d\'Água',
    location: 'Bloco B (Superior + Cisterna) • Sanitas Engenharia',
    description: 'Laudo emitido e certificado anexado',
    status: 'Laudo Emitido',
    statusType: 'certified',
    progressPercentage: 100,
    scheduledTime: 'Potabilidade aprovada',
    priority: 'Normal',
    hasCertificate: true,
    technicians: [{ initials: 'SE' }],
  }
];
